name: tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install, build, and test
      run: |
        yarn
        yarn build
        yarn test